version: '3.1'

services:
  db_pg:
    volumes:
      - ./pg_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  db_my:
    volumes:
      - ./my_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    command: --secure-file-priv="/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_DATABASE: geoip2
      MYSQL_ROOT_PASSWORD: password
